"""Initial schema

Revision ID: 190199e2dba5
Revises: 9f6c2edb7a10
Create Date: 2025-03-01 10:38:49.584136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '190199e2dba5'
down_revision: Union[str, None] = '9f6c2edb7a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('ratingMin', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('ratingMax', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'ratingMax')
    op.drop_column('questions', 'ratingMin')
    # ### end Alembic commands ###
