# docker-compose.yaml
version: "3.9"
services:
  db:
    image: postgres:15
    container_name: civibackend_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: civiform_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
